# Generated by Django 4.0.5 on 2022-06-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_rename_date_created_tournament_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(verbose_name='Starting on date'),
        ),
    ]
