# Generated by Django 4.0.5 on 2022-06-17 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_rounds_tournament_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='max_players',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(2)]),
        ),
    ]
