# Generated by Django 4.0.5 on 2022-06-17 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_alter_duel_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
    ]
