# Generated by Django 4.0.5 on 2022-06-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_alter_duel_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='max_rounds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='duel',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
