# Generated by Django 4.0.5 on 2022-06-17 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0012_duel_max_rounds_duel_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
