# Generated by Django 4.0.5 on 2022-06-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_alter_duel_player1_alter_duel_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_duels', to='tournament.duel'),
        ),
    ]
