# Generated by Django 4.0.5 on 2022-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_alter_duel_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
