# Generated by Django 4.0.5 on 2022-06-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_tournament_current_round'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
